---
- name: Create users
  user:
    name: "{{ item.name | mandatory }}"
    uid: "{{ item.uid | mandatory }}"
    password: "{{ item.password | default('!') }}"
    groups: "{{ item.groups | default('') }}"
    comment: "{{ item.comment | default(item.name) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: "{{ item.state | default('present') }}"
    remove: "{{ (item.state is defined and item.state == 'absent') | ternary('yes', 'no') }}"
  with_items:
    - "{{ create_users_users }}"
  register: creating_users

- name: Get paths of public keys of each user as a variable
  set_fact:
    keys: "{{ item }}"
  with_fileglob:
    - public_keys/*
  when: creating_users | success

- name: Add the public key to the authorized key for each user
  authorized_key:
    user: "{{ item[0].name }}"
    key: "{{ lookup('file', item[1]) }}"
  with_nested:
    - create_users_users
    - keys
  when: creating_users | success and item[1] | search(item[0].name)
